version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: ./src/Rapidata.Web/Dockerfile
    ports:
      - 5000:80

    volumes:
      - ~/.aws:/aws
  
  admin:
    build:
      context: .
      dockerfile: ./src/Rapidata.Admin/Dockerfile
    ports:
      - 5001:80

    volumes:
      - ~/.aws:/aws

  workflow:
    build:
      context: .
      dockerfile: ./src/Rapidata.Workflow/Dockerfile

